ALTER TABLE projets ADD COLUMN IF NOT EXISTS duree INT;
ALTER TABLE projets ADD COLUMN IF NOT EXISTS budget DECIMAL(10,2);
ALTER TABLE activites ADD COLUMN IF NOT EXISTS statut VARCHAR(50) NOT NULL DEFAULT 'en cours';

